import React, { useState } from 'react';
import { motion } from 'motion/react';
import { 
  FileText, 
  Plus, 
  Trash2, 
  Download, 
  Eye, 
  Building2, 
  Compass, 
  TrendingUp, 
  User as UserIcon,
  Search
} from 'lucide-react';
import { Report, Property } from '../types';

interface ReportsViewProps {
  reports: Report[];
  properties: Property[];
  onGenerateReport: (report: Partial<Report>) => Promise<void>;
  onDeleteReport?: (id: string) => Promise<void>; // optional helper
}

export default function ReportsView({
  reports,
  properties,
  onGenerateReport,
  onDeleteReport
}: ReportsViewProps) {
  const [showModal, setShowModal] = useState(false);
  const [searchQuery, setSearchQuery] = useState('');
  
  // Form states
  const [reportTitle, setReportTitle] = useState('');
  const [selectedPropertyId, setSelectedPropertyId] = useState('');
  const [reportType, setReportType] = useState<'Full Investment' | 'Market Analysis' | 'Competitor Intelligence' | 'Custom'>('Full Investment');
  const [reportFormat, setReportFormat] = useState<'PDF' | 'DOCX'>('PDF');

  // Filter reports
  const filteredReports = reports.filter(r => 
    r.title.toLowerCase().includes(searchQuery.toLowerCase()) || 
    r.propertyName.toLowerCase().includes(searchQuery.toLowerCase())
  );

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!reportTitle || !selectedPropertyId) return;

    await onGenerateReport({
      title: reportTitle,
      propertyId: selectedPropertyId,
      type: reportType,
      format: reportFormat
    });

    setShowModal(false);
    setReportTitle('');
    setSelectedPropertyId('');
  };

  return (
    <div className="space-y-6 text-slate-800 p-6 max-w-7xl mx-auto font-sans">
      
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-slate-900 flex items-center gap-2">
            <FileText className="h-6 w-6 text-indigo-600" />
            Report Generator History
          </h1>
          <p className="text-sm text-slate-500 mt-1">
            Browse structured asset summaries, yield forecasts, and city expansion audits generated by the specialized report engine.
          </p>
        </div>

        <button
          onClick={() => {
            setReportTitle('');
            setSelectedPropertyId(properties[0]?.id || '');
            setShowModal(true);
          }}
          className="inline-flex items-center space-x-2 bg-indigo-600 hover:bg-indigo-500 text-white font-semibold px-4 py-2.5 rounded-xl text-sm transition shadow-md shadow-indigo-600/10 cursor-pointer animate-fade-in"
        >
          <Plus className="h-4 w-4" />
          <span>Assemble New Report</span>
        </button>
      </div>

      {/* Reports ledger empty state */}
      {reports.length === 0 ? (
        <div className="py-20 text-center bg-white border border-slate-200 rounded-2xl max-w-2xl mx-auto shadow-sm">
          <div className="p-4 bg-indigo-50 text-indigo-600 rounded-2xl w-fit mx-auto mb-4">
            <FileText className="h-10 w-10" />
          </div>
          <h3 className="text-lg font-bold text-slate-900">No reports generated</h3>
          <p className="text-xs text-slate-500 max-w-md mx-auto mt-2 leading-relaxed">
            There are no documents recorded in your reports history directory. Run the assembler to bundle your property deeds, landmark vectors, and financial variables.
          </p>
          <button
            onClick={() => setShowModal(true)}
            className="mt-5 inline-flex items-center space-x-1.5 text-xs bg-indigo-600 hover:bg-indigo-500 text-white px-4 py-2 rounded-xl transition cursor-pointer"
          >
            <Plus className="h-3.5 w-3.5" />
            <span>Generate First Report</span>
          </button>
        </div>
      ) : (
        /* Main Ledger Table with Quick Filters */
        <div className="space-y-4">
          
          {/* Search box row */}
          <div className="max-w-md">
            <div className="relative">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-450" />
              <input
                type="text"
                placeholder="Search report titles or properties..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="w-full pl-9 pr-3 py-2 bg-white border border-slate-200 rounded-xl text-xs placeholder-slate-400 focus:outline-none focus:border-indigo-500 text-slate-700 transition shadow-sm"
              />
            </div>
          </div>

          {/* Ledger Table */}
          <div className="border border-slate-200 rounded-2xl bg-white overflow-hidden shadow-sm">
            <div className="overflow-x-auto">
              <table className="w-full text-left border-collapse text-xs">
                <thead>
                  <tr className="border-b border-slate-200 bg-slate-50/70 text-slate-500 font-mono font-semibold uppercase tracking-wider">
                    <th className="p-4">Report Title</th>
                    <th className="p-4">Target Property Node</th>
                    <th className="p-4">Report Category</th>
                    <th className="p-4">Created By</th>
                    <th className="p-4">Status</th>
                    <th className="p-4">Created Date</th>
                    <th className="p-4 text-right">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {filteredReports.map((report) => (
                    <tr 
                      key={report.id}
                      className="border-b border-slate-100 hover:bg-slate-50/50 transition text-slate-600"
                    >
                      {/* Title */}
                      <td className="p-4">
                        <div className="flex items-center space-x-3">
                          <div className="p-2 bg-rose-50 rounded-lg text-rose-600 border border-rose-100 shrink-0">
                            <FileText className="h-4.5 w-4.5" />
                          </div>
                          <span className="font-semibold text-slate-800 truncate max-w-xs md:max-w-md" title={report.title}>
                            {report.title}
                          </span>
                        </div>
                      </td>

                      {/* Property */}
                      <td className="p-4">
                        <div className="flex items-center space-x-1.5 text-slate-700 font-medium">
                          <Building2 className="h-3.5 w-3.5 text-slate-400" />
                          <span>{report.propertyName}</span>
                        </div>
                      </td>

                      {/* Category */}
                      <td className="p-4">
                        <span className="text-slate-550">{report.type}</span>
                      </td>

                      {/* Author */}
                      <td className="p-4">
                        <div className="flex items-center space-x-1.5 text-slate-700 font-semibold">
                          <UserIcon className="h-3.5 w-3.5 text-slate-450" />
                          <span>{report.createdByName}</span>
                        </div>
                      </td>

                      {/* Status */}
                      <td className="p-4">
                        <span className={`inline-flex items-center px-2 py-0.5 rounded-full text-[9px] font-bold uppercase tracking-wider font-mono border ${
                          report.status === 'Completed' ? 'bg-emerald-50 border-emerald-150 text-emerald-700' :
                          report.status === 'Generating' ? 'bg-indigo-50 border-indigo-150 text-indigo-700 animate-pulse' :
                          'bg-rose-50 border-rose-150 text-rose-700'
                        }`}>
                          <span className={`h-1.5 w-1.5 rounded-full mr-1 ${
                            report.status === 'Completed' ? 'bg-emerald-500' :
                            report.status === 'Generating' ? 'bg-indigo-500' : 'bg-rose-500'
                          }`} />
                          {report.status}
                        </span>
                      </td>

                      {/* Created Date */}
                      <td className="p-4 text-slate-500 font-mono text-[11px]">
                        {new Date(report.createdAt).toLocaleDateString(undefined, {
                          month: 'short',
                          day: 'numeric',
                          year: 'numeric'
                        })}
                      </td>

                      {/* Actions */}
                      <td className="p-4 text-right">
                        <div className="flex items-center justify-end space-x-1">
                          <button
                            onClick={() => alert(`Opening PDF visual display for: ${report.title}`)}
                            className="p-1.5 text-slate-400 hover:text-slate-800 hover:bg-slate-50 rounded-lg transition cursor-pointer"
                            title="Preview"
                          >
                            <Eye className="h-4 w-4" />
                          </button>
                          <button
                            onClick={() => alert(`Downloading PDF chunk: ${report.title}`)}
                            className="p-1.5 text-slate-400 hover:text-slate-800 hover:bg-slate-50 rounded-lg transition cursor-pointer"
                            title="Download"
                          >
                            <Download className="h-4 w-4" />
                          </button>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      )}

      {/* Report Creation Modal */}
      {showModal && (
        <div className="fixed inset-0 bg-slate-900/55 backdrop-blur-xs flex items-center justify-center p-4 z-50">
          <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            className="bg-white border border-slate-200 rounded-2xl w-full max-w-md p-6 shadow-2xl space-y-4"
          >
            <div className="flex items-center justify-between border-b border-slate-100 pb-3">
              <h3 className="text-lg font-bold text-slate-900 flex items-center gap-2">
                <FileText className="h-5 w-5 text-indigo-600" />
                Assemble property report
              </h3>
              <button onClick={() => setShowModal(false)} className="text-slate-400 hover:text-slate-800 transition cursor-pointer">✕</button>
            </div>

            <form onSubmit={handleSubmit} className="space-y-4 text-left">
              
              {/* Report Title */}
              <div>
                <label className="block text-xs font-semibold text-slate-550 font-mono uppercase mb-1">Report Title</label>
                <input
                  type="text"
                  required
                  value={reportTitle}
                  onChange={(e) => setReportTitle(e.target.value)}
                  className="w-full px-3 py-2 bg-slate-50 border border-slate-200 rounded-xl text-slate-800 placeholder-slate-400 focus:outline-none focus:border-indigo-500 focus:bg-white text-sm transition"
                  placeholder="e.g. Bridgeview Court Investment Report"
                />
              </div>

              {/* Target Property */}
              <div>
                <label className="block text-xs font-semibold text-slate-550 font-mono uppercase mb-1">Target Asset Node</label>
                <select
                  required
                  value={selectedPropertyId}
                  onChange={(e) => setSelectedPropertyId(e.target.value)}
                  className="w-full px-3 py-2 bg-slate-50 border border-slate-200 rounded-xl text-slate-800 focus:outline-none focus:border-indigo-500 focus:bg-white text-sm transition"
                >
                  <option value="" disabled>-- Select target portfolio --</option>
                  {properties.map(p => (
                    <option key={p.id} value={p.id}>{p.name}</option>
                  ))}
                </select>
              </div>

              {/* Grid: Type and Format */}
              <div className="grid grid-cols-2 gap-4">
                {/* Report Type */}
                <div>
                  <label className="block text-xs font-semibold text-slate-550 font-mono uppercase mb-1">Audit Type</label>
                  <select
                    value={reportType}
                    onChange={(e) => setReportType(e.target.value as any)}
                    className="w-full px-3 py-2 bg-slate-50 border border-slate-200 rounded-xl text-slate-800 focus:outline-none focus:border-indigo-500 focus:bg-white text-sm transition"
                  >
                    <option value="Full Investment">Investment Yield</option>
                    <option value="Market Analysis">Market Proximity</option>
                    <option value="Competitor Intelligence">Competitor Grid</option>
                    <option value="Custom">Custom Assessment</option>
                  </select>
                </div>

                {/* File Format */}
                <div>
                  <label className="block text-xs font-semibold text-slate-550 font-mono uppercase mb-1">Export Format</label>
                  <select
                    value={reportFormat}
                    onChange={(e) => setReportFormat(e.target.value as any)}
                    className="w-full px-3 py-2 bg-slate-50 border border-slate-200 rounded-xl text-slate-800 focus:outline-none focus:border-indigo-500 focus:bg-white text-sm transition"
                  >
                    <option value="PDF">PDF Ledger</option>
                    <option value="DOCX">DOCX Template</option>
                  </select>
                </div>
              </div>

              {/* Informative notice */}
              <div className="bg-indigo-50 border border-indigo-100 rounded-xl p-3 text-[11px] text-indigo-700 leading-relaxed">
                Assembling report will query associated survey files, proximity vectors, and regional pricing spreads dynamically.
              </div>

              {/* Action Buttons */}
              <div className="flex items-center justify-end space-x-2 border-t border-slate-100 pt-3 mt-4">
                <button
                  type="button"
                  onClick={() => setShowModal(false)}
                  className="px-4 py-2 text-xs font-semibold text-slate-500 hover:text-slate-800 transition cursor-pointer"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="bg-indigo-600 hover:bg-indigo-500 text-white font-semibold px-4 py-2 rounded-xl text-xs transition cursor-pointer"
                >
                  Request Assembly
                </button>
              </div>

            </form>
          </motion.div>
        </div>
      )}

    </div>
  );
}
